# Generated by Django 6.0.2 on 2026-02-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='sabzeno.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
