# Generated by Django 6.0.2 on 2026-02-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
    ]
