# Generated by Django 6.0.2 on 2026-02-05 10:35

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0002_remove_product_features_productfeature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cerated',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cerated',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='بروز رسانی زمان'),
        ),
    ]
