# Generated by Django 6.0.2 on 2026-02-08 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0002_remove_users_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('full_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='ادرس کامل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
