# Generated by Django 6.0.2 on 2026-02-09 09:39

import sabzeno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0003_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'ادرس', 'verbose_name_plural': 'ادرس ها'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=sabzeno.models.upload_to),
        ),
    ]
