# Generated by Django 6.0.2 on 2026-02-09 10:06

import django_resized.forms
import sabzeno.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0004_alter_address_options_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, None], upload_to=sabzeno.models.upload_to),
        ),
    ]
