# Generated by Django 6.0.2 on 2026-02-09 10:12

import django_resized.forms
import sabzeno.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0007_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to=sabzeno.models.upload_to),
        ),
    ]
