# Generated by Django 6.0.2 on 2026-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzeno', '0008_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weoght',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
